# Travis CI
dist: xenial
language: python

python:
  - "3.6"

cache:
  - pip

install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - python setup.py develop

services:
  - redis-server

script:
  - pushd demo
  - pytest demo --cov=demo --cov=django_plotly_dash --cov-report term-missing

after_success:
  - coveralls
