# Travis CI
language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - python setup.py develop

script:
  - pushd demo
  - pytest demo --cov=demo --cov=django_plotly_dash --cov-report term-missing