#!/usr/bin/env bash
#
# Create a virtualenv. Note that python 3.6 is currently the minimal requirement
#
# Stop on error, rather than continue and trash the environment
set -e
#
# Default to 3.6 but allow override
DEFAULT_PYTHON_VER=3.8
PYTHON_VER=${1:-$DEFAULT_PYTHON_VER}
#
virtualenv -p python${PYTHON_VER} env
#
source env/bin/activate
#
pip install -r requirements.txt
pip install -r dev_requirements.txt
#
python setup.py develop
