#!/usr/bin/env bash
#
# Create a virtualenv. Note that python 3.6 is the minimal requirement
#
virtualenv -p python3.6 env
#
source env/bin/activate
#
pip install -r requirements.txt
pip install -r dev_requirements.txt
#
python setup.py develop
