#!/usr/bin/env bash
#
source env/bin/activate
cd demo
./manage.py migrate
./manage.py shell < configdb.py # Add a superuser if needed
./manage.py collectstatic -i "*.py" -i "*.pyc" --noinput --link
./manage.py runserver
