# Generated by Django 2.0.5 on 2018-05-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_plotly_dash', '0002_simple_example_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashapp',
            name='save_on_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dashapp',
            name='base_state',
            field=models.TextField(default='{}'),
        ),
    ]
