# Generated by Django 2.0.5 on 2018-05-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_plotly_dash', '0003_auto_20180514_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatelessApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
            ],
        ),
    ]
